# Generated by Django 6.0.7 on 2026-08-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_notifications', models.BooleanField(default=True)),
                ('assignment_notifications', models.BooleanField(default=True)),
                ('quiz_notifications', models.BooleanField(default=True)),
                ('alec_companion', models.BooleanField(default=True)),
                ('alec_insights', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
