# Generated by Django 6.0.7 on 2026-07-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
