# Generated by Django 6.0.7 on 2026-08-07 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alec', '0001_initial'),
        ('classroom', '0003_streampost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alecmessage',
            name='conversation',
        ),
        migrations.CreateModel(
            name='AlecMemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_average', models.FloatField(default=0)),
                ('quiz_average', models.FloatField(default=0)),
                ('assignment_average', models.FloatField(default=0)),
                ('completed_quizzes', models.PositiveIntegerField(default=0)),
                ('graded_assignments', models.PositiveIntegerField(default=0)),
                ('overdue_count', models.PositiveIntegerField(default=0)),
                ('task_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alec_memory_snapshots', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alec_memory_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AlecConversation',
        ),
        migrations.DeleteModel(
            name='AlecMessage',
        ),
    ]
