# Generated by Django 6.0.7 on 2026-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alec', '0003_alecmemoryevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alecmemoryevent',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
