# Generated by Django 6.0.7 on 2026-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alec', '0004_alecmemoryevent_acknowledged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alecmemorysnapshot',
            old_name='task_count',
            new_name='total_task_count',
        ),
    ]
