# Generated by Django 6.0.7 on 2026-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alec', '0005_rename_task_count_alecmemorysnapshot_total_task_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alecmemoryevent',
            name='event_type',
            field=models.CharField(choices=[('quiz_completed', 'Quiz Completed'), ('assignment_submitted', 'Assignment Submitted'), ('grade_changed', 'Grade Changed'), ('task_overdue', 'Task Became Overdue'), ('classroom_revisited', 'Classroom Revisited'), ('performance_improved', 'Performance Improved'), ('performance_declined', 'Performance Declined'), ('quiz_performance_changed', 'Quiz Performance Changed'), ('assignment_performance_changed', 'Assignment Performance Changed')], max_length=50),
        ),
    ]
