# Generated by Django 6.0.7 on 2026-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignmentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
